[project]
name = "motion-system"
version = "0.1.0"
description = "Detect motion from video, camera"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mediapipe>=0.10.32",
    "numpy>=2.4.2",
    "opencv-python>=4.13.0.90",
    "ultralytics>=8.4.9",
]
